apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-app
  template:
    metadata:
      labels:
        app: react-app
    spec:
      containers:
        - name: react-app
          image: aksregistery01.azure.io/raaaaaaai/react-django:react-image
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: react-service
spec:
  selector:
    app: react-app
  ports:
    - port: 3000
      targetPort: 3000
  type: LoadBalancer

  